apiVersion: v1
kind: Pod
metadata:
  name: probe-hostns
  namespace: chaosify-tests
spec:
  hostPID: true
  hostNetwork: true
  containers:
  - name: probe
    image: alpine:3.19
    command: ["sleep", "3600"]
  restartPolicy: Never
