apiVersion: v1
kind: Pod
metadata:
  name: probe-privileged
  namespace: chaosify-tests
spec:
  containers:
  - name: probe
    image: alpine:3.19
    command: ["sleep", "3600"]
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
  restartPolicy: Never
