apiVersion: v1
kind: Pod
metadata:
  name: probe-nettest
  namespace: chaosify-tests
spec:
  containers:
  - name: probe
    image: nicolaka/netshoot:latest
    command: ["sleep", "3600"]
  restartPolicy: Never
