// Implements “chaosclaw probe detect” — the runtime detection primitive.
// Submits a pod, execs a threat command, polls the configured alert source, and
// reports whether the runtime security tool fired an alert.
import { basename } from 'node:path'
import type { Command } from 'commander'
import { RuntimeScenarioExecutor } from '../../../core/scenarios/exec/runtime-executor.js'
import { RuntimeValidationEngine } from '../../../core/validation/runtime-validator.js'
import { buildAlertSource } from '../../../core/alert-sources/index.js'
import { loadPodManifest, resolveFirstContainer, ensureNamespace } from '../../../core/scenarios/exec/pod-runner.js'
import { CleanupManager } from '../../../core/teardown/cleanup.js'
import { EvidenceBuilder } from '../../../core/teardown/evidence-builder.js'
import type { RuntimeScenarioDefinition, RuntimeExpectedOutcomeType } from '../../../types/runtime-scenario.js'
import { header, field, section, indent, outcomeLabel, blank, printAlertSection, printCleanupWarning } from '../../output.js'
import { buildKubeConfig } from '../recon/utils/shared.js'
import { DEFAULT_PROBE_NAMESPACE } from './utils/shared.js'
import chalk from 'chalk'

const DEFAULT_OBSERVATION_WINDOW_S = 10
const DEFAULT_POD_TIMEOUT_S = 60

const VALID_EXPECTS = ['alert_fired', 'action_blocked', 'no_alert'] as const
type DetectExpect = (typeof VALID_EXPECTS)[number]

/**
 * Attaches the "detect" subcommand to the probe command group.
 * @param probe The probe command group to attach to.
 */
export function detect(probe: Command): void {
    probe
        .command('detect')
        .description('Submit a pod, exec a threat command, and verify the runtime security tool fires an alert')
        .requiredOption('--pod <path>', 'Pod manifest to submit (YAML or JSON, generated by OpenClaw)')
        .requiredOption('--run <command>', 'Command to exec inside the container to trigger the threat')
        .option('--container <name>', 'Container to exec into (default: first container in the pod spec)')
        .requiredOption('--expect <outcome>', 'Expected outcome: alert_fired, action_blocked, no_alert')
        .option('--alert-source <tool>', 'Runtime alert source to poll: none (default), falco, tetragon, kubearmor', 'none')
        .option('--observation-window <seconds>', `Seconds to wait for an alert after the exec (default: ${DEFAULT_OBSERVATION_WINDOW_S})`, String(DEFAULT_OBSERVATION_WINDOW_S))
        .option('--pod-timeout <seconds>', `Seconds to wait for the pod to reach Running (default: ${DEFAULT_POD_TIMEOUT_S})`, String(DEFAULT_POD_TIMEOUT_S))
        .option('--context <name>', 'Kubernetes context to use')
        .option('--namespace <name>', 'Test namespace', DEFAULT_PROBE_NAMESPACE)
        .option('--output <path>', 'Write JSON evidence artifact to file')
        .option('--format <mode>', 'Output mode: table, json', 'table')
        .option('--cleanup <mode>', 'Cleanup mode: always, on-success', 'always')
        .action(async (opts: {
            pod: string
            run: string
            container?: string
            expect: string
            alertSource: string
            observationWindow: string
            podTimeout: string
            context?: string
            namespace: string
            output?: string
            format: string
            cleanup: string
        }) => {
            if (!VALID_EXPECTS.includes(opts.expect as DetectExpect)) {
                console.error(`\nError\n  --expect must be one of: ${VALID_EXPECTS.join(', ')}. Got: "${opts.expect}"`)
                process.exit(4)
            }

            // Warn early when no alert source is configured so the operator understands the limitation.
            if (opts.alertSource === 'none' && opts.format !== 'json') {
                console.log(chalk.yellow('\n[WARN] No alert source configured (--alert-source none)'))
                console.log(chalk.yellow('       The threat command will execute but the observed outcome will always be "no_alert".'))
                console.log(chalk.yellow('       Use --alert-source falco, tetragon, or kubearmor to poll a real detection tool.\n'))
            }

            // Build a synthetic RuntimeScenarioDefinition wrapping the user-supplied manifest.
            const scenario = await loadDetectScenario(opts.pod, opts.run, opts.container, opts.expect as DetectExpect)

            const { kc, clusterContext } = buildKubeConfig(opts.context)

            await ensureNamespace(kc, opts.namespace)

            const observationWindowMs = parseInt(opts.observationWindow, 10) * 1_000
            const podTimeoutMs = parseInt(opts.podTimeout, 10) * 1_000
            // Hard ceiling: pod startup + observation window + 5s grace.
            const timeoutMs = podTimeoutMs + observationWindowMs + 5_000

            // Wire the runtime executor to the chosen alert source adapter.
            const executor = new RuntimeScenarioExecutor(kc, buildAlertSource(opts.alertSource, kc))
            const validator = new RuntimeValidationEngine()
            const cleanup = new CleanupManager(kc)
            const builder = new EvidenceBuilder({
                clusterContext,
                startedAt: new Date().toISOString(),
            })

            if (opts.format !== 'json') {
                header('ChaosClaw Detect')
                field('Cluster Context', clusterContext)
                field('Pod Manifest', opts.pod)
                field('Command', opts.run)
                if (opts.container) field('Container', opts.container)
                field('Expect', opts.expect)
                field('Alert Source', opts.alertSource)
                field('Observation Window', `${opts.observationWindow}s`)
                field('Test Namespace', opts.namespace)
                section('Running')
            }

            // Run the full scenario (submit pod â†’ exec threat â†’ observe alert).
            const execution = await executor.execute(scenario, {
                namespace: opts.namespace,
                observationWindowMs,
                timeoutMs,
            })
            const validation = validator.validate(scenario, execution)

            // Only add the pod to cleanup targets if it was actually created before any failure.
            const createdResources = execution.createdResourceName
                ? [{ kind: 'Pod' as const, name: execution.createdResourceName, namespace: opts.namespace }]
                : []

            const shouldCleanup = opts.cleanup === 'always'
                || (opts.cleanup === 'on-success' && validation.status === 'Pass')
            const cleanupResult = shouldCleanup
                ? await cleanup.cleanup(createdResources)
                : { status: 'skipped' as const, remainingResources: [] }

            const result = {
                scenarioId: scenario.id,
                version: scenario.version,
                status: validation.status,
                // Replace underscores with spaces to produce a readable expected-outcome string.
                expectedOutcome: opts.expect.replace(/_/g, ' '),
                observedOutcome: validation.observedOutcome,
                cleanupStatus: cleanupResult.status,
                startedAt: execution.startedAt,
                endedAt: execution.endedAt,
                // Prefer the structured alert detail over the raw response string when available.
                rawResponse: execution.alertDetail
                    ? JSON.stringify(execution.alertDetail)
                    : execution.rawResponse,
                manifestSnapshot: execution.manifestSnapshot,
                likelyIssue: validation.likelyIssue,
            }

            builder.addResult(result)
            const evidence = builder.build(new Date().toISOString())

            if (opts.format === 'json') {
                console.log(JSON.stringify(evidence, null, 2))
                process.exit(validation.status === 'Pass' ? 0 : 1)
            }

            indent(`${outcomeLabel(result.status)} ${scenario.id}`)

            if (execution.alertDetail) printAlertSection(execution.alertDetail)

            section('Summary')
            indent(`Status:   ${result.status}`)
            indent(`Expected: ${result.expectedOutcome}`)
            indent(`Observed: ${result.observedOutcome}`)
            if (result.likelyIssue) indent(`Issue:    ${result.likelyIssue}`)

            printCleanupWarning(cleanupResult.remainingResources)

            if (opts.output) {
                await builder.writeToFile(opts.output, evidence)
                section('Artifacts')
                indent(`JSON report written to: ${opts.output}`)
            }

            blank()
            process.exit(validation.status === 'Pass' ? 0 : 1)
        })
}

// Construct a minimal RuntimeScenarioDefinition from CLI options so the detect command
// can reuse the same execution pipeline as built-in scenarios.
async function loadDetectScenario(
    podPath: string,
    run: string,
    container: string | undefined,
    expect: DetectExpect,
): Promise<RuntimeScenarioDefinition> {
    const manifest = await loadPodManifest(podPath)
    // Fall back to the first container in the spec when --container is not specified.
    const resolvedContainer = container ?? resolveFirstContainer(manifest)
    if (!resolvedContainer) {
        console.error('\nError\n  Could not determine container name â€” specify --container or ensure the pod spec includes named containers')
        process.exit(4)
    }

    return {
        id: `custom:detect:${basename(podPath)}`,
        version: 1,
        name: basename(podPath),
        description: 'User-submitted detection test',
        category: 'detective',
        controlObjective: 'User-defined',
        prerequisites: [],
        manifest,
        execStep: {
            container: resolvedContainer,
            // Split the run string on spaces to produce the exec argv array.
            command: run.split(' '),
        },
        expectedOutcome: { type: expect as RuntimeExpectedOutcomeType },
        cleanup: { deleteCreatedResources: true },
        safety: { level: 'low', namespaceScoped: true },
    }
}
